inherits = "noctalia"

# Override keyword color
"string" = { fg = "tertiary" }
"string.regexp" = { fg = "tertiaryContainer" }
"string.special" = { fg = "tertiary" }
"string.special.symbol" = { fg = "tertiary" }
"string.special.path" = { fg = "secondary", underline = { color = "secondary", style = "line" } }

"constant.character" = { fg = "tertiary", modifiers = ["bold"] }
"constant.character.escape" = { fg = "tertiary", modifiers = ["bold"] }

"ui.virtual.jump-label" = { fg = "info", modifiers = ["bold"] }

"ui.statusline" = { fg = "onSurface" }
"ui.statusline.inactive" = { fg = "onSurface" }
"ui.statusline.normal" = { fg = "onPrimary", bg = "primary", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "onTertiary", bg = "tertiary", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "onSecondary", bg = "secondary", modifiers = ["bold"] }

[palette]
error = "#ff5555"
warning = "#ffaa33"
