inherits = "noctalia"

# Override keyword color
"string" = { fg = "tertiary" }
"string.regexp" = { fg = "tertiaryContainer" }
"string.special" = { fg = "tertiary" }
"string.special.symbol" = { fg = "tertiary" }
"string.special.path" = { fg = "secondary", underline = { color = "secondary", style = "line" } }

[palette]
error = "#ff5555"
warning = "#ffaa33"
